    
    <!-- Define la codificación de caracteres -->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <!-- Define el autor del documento -->
    <meta name="author" content="Felix Prado Rubio" />
    <!-- Define el programa con el que se ha generado el documento -->
    <meta name="generator" content="NetBeans 8.2" />
    <!-- Define el copyright del documento -->
    <meta name="copyright" content="DWES" />
    <!-- Define las palabras claves del contenido del documento -->
    <meta name="keywords" content="Proyecto Final" />
    <!-- Define una breve descripción del sitio -->
    <meta name="description" content="Proyecto de final de curso hibernate" />
